---

- name: install packages
  yum: name={{ item }} 
  with_items: 
  - yum-utils
  become: true

## Install EPEL

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}" 
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: yum update 
  shell: yum -y --exclude=centos-release*  update 
  become: true

- name: install prerequisites
  yum: name={{ item }}
  with_items: 
  - pygpgme
  - curl
  - ntp
  become: true

- name: update ntp time
  shell: ntpdate pool.ntp.org
  become: true

- name: start and enable ntp
  service: 
    name: ntpd
    enabled: yes
  become: true

- name: Add el6 YUM rep
  command: sudo curl --fail -sSLo /etc/yum.repos.d/passenger.repo https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo


# Install Passenger + Apache module
- name : Install Passenger + Apache module
  shell: sudo yum install -y mod_passenger || sudo yum-config-manager --enable cr && sudo yum install -y mod_passenger
 
# Validating the installtion
- name: Validate Install
  command: /usr/bin/passenger-config validate-install

- name: Restart Apache2
  service:  name=httpd state=restarted

